cf1:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  crazyflie_M1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: crazyflie_M1_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}